#'
#'This is a object cointains all the data used and generated by the bulkRNASeq
#'pipeline
#'@slot data  contains the tables: raw data table and normalized table
#'@slot pca contains pca results
#'@slot dgenes DE genes results
#'@slot parameters  contains regarded parameters
#'@slot design contains the design matrix
#'
BObj <- setClass("LRObj", slots=list(data="list",
                                     dgenes = "list",
                                     parameters="list",
                                     design="numeric"))
